# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/node:10.16

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

      # run tests!
      # - run: yarn test

  publish_from_git:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: 'npx lerna publish from-git --yes'

  publish_from_package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: 'npx lerna publish from-package --yes'

  deploy_gh_pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "dc:77:1e:34:a6:82:c0:9f:1a:41:40:86:af:6c:90:db"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "anthony.simone7@gmail.com"
            git config user.name "anthonysimone"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn run gh-pages

workflows:
  version: 2
  only_build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^@asimone.*/
            branches:
              ignore: release

  # build_publish:
  #   jobs:
  #     - build:
  #         filters:
  #           tags:
  #             ignore: /.*/
  #           branches:
  #             only: release
  #     - publish:
  #         requires:
  #           - build
  #         filters:
  #           tags:
  #             ignore: /.*/
  #           branches:
  #             only: release

  build_publish_from_package:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: release
      - publish_from_package:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only: release
      - deploy_gh_pages:
          requires:
            - build
            - publish_from_package
          filters:
            tags:
              ignore: /.*/
            branches:
              only: release


  # build_publish_from_git:
  #   jobs:
  #     - build:
  #         filters:
  #           tags:
  #             only: /^@asimone.*/
  #           branches:
  #             ignore: /.*/
  #     - publish_from_git:
  #         requires:
  #           - build
  #         filters:
  #           tags:
  #             only: /^@asimone.*/
  #           branches:
  #             ignore: /.*/